name: deepmimo
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.6.4
  - intel-openmp=2023.1.0
  - libffi=3.4.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - openssl=3.0.17
  - pip=25.2
  - python=3.12.9
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tzdata=2025a
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.2.2
      - aenum==3.1.16
      - ajsonrpc==1.2.0
      - anyio==4.9.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - backports-strenum==1.2.8
      - beautifulsoup4==4.13.3
      - bidict==0.23.1
      - bleach==6.2.0
      - bottle==0.13.4
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.7
      - colorama==0.4.6
      - comm==0.2.2
      - construct==2.10.68
      - contourpy==1.3.2
      - cycler==0.12.1
      - debugpy==1.8.13
      - decorator==5.2.1
      - defusedxml==0.7.1
      - distlib==0.3.9
      - docopt==0.6.2
      - edgeimpulse==1.0.18
      - edgeimpulse-api==1.71.58
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - fonttools==4.57.0
      - fqdn==1.5.1
      - future==1.0.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.71.0
      - h11==0.14.0
      - h5py==3.13.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - ipykernel==6.30.1
      - ipython==9.0.2
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.5
      - iso8601==2.1.0
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - jupytext==1.17.0
      - keras==3.9.2
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - mistune==3.1.3
      - ml-dtypes==0.5.1
      - namex==0.0.8
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.3.3
      - notebook-shim==0.2.4
      - numpy==2.1.3
      - onnx==1.17.0
      - opt-einsum==3.4.0
      - optree==0.14.1
      - overrides==7.7.0
      - packaging==25.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.2.1
      - platformdirs==4.3.7
      - platformio==6.1.18
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - protobuf==3.20.3
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pydantic==1.10.22
      - pyelftools==0.32
      - pygments==2.19.1
      - pykwalify==1.8.0
      - pyparsing==3.2.3
      - pyserial==3.5
      - python-dateutil==2.9.0.post0
      - python-engineio==4.12.2
      - python-json-logger==3.3.0
      - python-socketio==5.13.0
      - pywin32==311
      - pywinpty==3.0.0
      - pyyaml==6.0.2
      - pyzmq==26.3.0
      - referencing==0.36.2
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.0.0
      - rpds-py==0.24.0
      - ruamel-yaml==0.18.14
      - ruamel-yaml-clib==0.2.12
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - serial==0.0.97
      - simple-websocket==1.1.0
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - starlette==0.46.2
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - termcolor==3.0.1
      - terminado==0.18.1
      - tf2onnx==1.16.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.13.1
      - uri-template==1.3.0
      - urllib3==1.26.20
      - uvicorn==0.34.3
      - virtualenv==20.31.2
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - west==1.4.0
      - widgetsnbextension==4.0.13
      - wrapt==1.17.2
      - wsproto==1.2.0
prefix: C:\Users\Work\miniconda3\envs\deepmimo
